name: elite_laundry_customer_app
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_messaging: ^15.2.7
  firebase_storage: ^12.4.7

  # Additional useful packages for laundry app
  http: ^1.4.0
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  geocoding: ^4.0.0
  email_validator: ^3.0.0
  firebase_app_check: ^0.3.2+7
  cloud_functions: ^5.5.2
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^19.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-Regular.ttf

  assets:
    - assets/images/cargotruck.png
    - assets/images/logo.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21
