// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqp-dXaMHnIui9QupdkrEA7JSFCOEahQ8',
    appId: '1:264965810934:web:184af033f99b1f69081ad7',
    messagingSenderId: '264965810934',
    projectId: 'elite-laundry-station',
    authDomain: 'elite-laundry-station.firebaseapp.com',
    storageBucket: 'elite-laundry-station.firebasestorage.app',
    measurementId: 'G-T7N71TC5RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAluwy5MHmxqtA-dPXtc6ynxzFODZixFJo',
    appId: '1:264965810934:android:dd3c7e1cdcdc438d081ad7',
    messagingSenderId: '264965810934',
    projectId: 'elite-laundry-station',
    storageBucket: 'elite-laundry-station.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTUWNHr-InzD5nwzGKbUXT69qARbCDEOU',
    appId: '1:264965810934:ios:ce74e4c7e583b134081ad7',
    messagingSenderId: '264965810934',
    projectId: 'elite-laundry-station',
    storageBucket: 'elite-laundry-station.firebasestorage.app',
    iosBundleId: 'com.example.eliteLaundryCustomerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTUWNHr-InzD5nwzGKbUXT69qARbCDEOU',
    appId: '1:264965810934:ios:ce74e4c7e583b134081ad7',
    messagingSenderId: '264965810934',
    projectId: 'elite-laundry-station',
    storageBucket: 'elite-laundry-station.firebasestorage.app',
    iosBundleId: 'com.example.eliteLaundryCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqp-dXaMHnIui9QupdkrEA7JSFCOEahQ8',
    appId: '1:264965810934:web:50bdc94fd7383815081ad7',
    messagingSenderId: '264965810934',
    projectId: 'elite-laundry-station',
    authDomain: 'elite-laundry-station.firebaseapp.com',
    storageBucket: 'elite-laundry-station.firebasestorage.app',
    measurementId: 'G-QV35F5QGLM',
  );

}